---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  vars:
      # brew list
      homebrew_packages:
          - { name: ansible }
          - { name: ansible-lint }
          - { name: bitwarden-cli }
          - { name: curl }
          - { name: cloudflared }
          - { name: ffmpeg }
          - { name: gh }
          - { name: git }
          - { name: go }
          - { name: ioping }
          - { name: ipcalc }
          - { name: iperf }
          - { name: jq }
          - { name: mas }
          - { name: mysql }
          - { name: openssl }
          - { name: telnet }
          - { name: tree }
          - { name: unar }
          - { name: wget }
          - { name: zsh-autosuggestions }
          - { name: zsh-completions }
          - { name: zsh-syntax-highlighting }
      homebrew_cask_packages:
          - { name: alfred }
          - { name: caffeine }
          - { name: chatgpt }
          # - { name: cleanmymac } need to install clean my mac x manually
          - { name: clipy }
          - { name: discord }
          - { name: dropbox }
          - { name: firefox }
          - { name: geekbench }
          - { name: git-credential-manager }
          - { name: google-chrome }
          - { name: google-drive }
          - { name: google-japanese-ime }
          - { name: handbrake }
          - { name: iterm2 }
          - { name: libreoffice }
          - { name: microsoft-edge }
          - { name: obsidian }
          - { name: postman }
          - { name: rectangle }
          - { name: sequel-ace }
          - { name: spotify }
          - { name: visual-studio-code }
          - { name: wireshark }
          - { name: zoom }
      # mas list
      mac_app_store_apps:
          - { id: 497799835 } # Xcode
          - { id: 430255202 } # Mactracker
          - { id: 1604183938 } # Simple Metronome
          - { id: 412754595 } # SoundCloud
          - { id: 1462114288 } # Grammarly for Safari
          - { id: 1122008420 } # Table Tool
          - { id: 421131143 } # MPlayerX
          - { id: 1153157709 } # Speedtest
          - { id: 634148309 } # Logic Pro
          - { id: 472226235 } # LanScan
          - { id: 582840059 } # Wireless Signal
          - { id: 844918735 } # PicGIF Lite
          - { id: 425264550 } # Disk Speed Test
          - { id: 430207028 } # ClamXav
          - { id: 909760813 } # Who's On My WiFi
          - { id: 1423210932 } # Flow
          - { id: 405580712 } # StuffIt Expander
          - { id: 441258766 } # Magnet
          - { id: 425424353 } # The Unarchiver
          - { id: 568494494 } # Pocket
          - { id: 1352778147 } # Bitwarden
          - { id: 1455702185 } # ComicViewer
          - { id: 1295203466 } # Microsoft Remote Desktop
          - { id: 914182966 } # QuickNome
          - { id: 420874236 } # PDFOutliner
          - { id: 409201541 } # Pages
          - { id: 512505421 } # Snip
          - { id: 803453959 } # Slack
          - { id: 1036029895 } # Music Convert-Audio Converter
          - { id: 642142422 } # Premium Fonts
          - { id: 405399194 } # Kindle Classic
          - { id: 1024640650 } # CotEditor
          - { id: 408981434 } # iMovie
          - { id: 409203825 } # Numbers
          - { id: 539883307 } # LINE
          - { id: 409183694 } # Keynote
          - { id: 1030400150 } # Kortext
          - { id: 1560727432 } # Microsoft Bing for Safari
          - { id: 1518036000 } # Sequel Ace
      # defaults read
      osx_settings:
          #################################
          # General
          #################################
          # InterfaceStyle
          - {
                domain: NSGlobalDomain,
                key: AppleInterfaceStyle,
                type: string,
                value: "Dark",
            }
          #################################
          # Finder
          #################################
          # show all extensions
          - {
                domain: NSGlobalDomain,
                key: AppleShowAllExtensions,
                type: bool,
                value: true,
            }
          # Show Status bar in Finder (need "killall Finder")
          - {
                domain: com.apple.finder,
                key: ShowStatusBar,
                type: bool,
                value: true,
            }
          # Show Path bar in Finder
          - {
                domain: com.apple.finder,
                key: ShowPathbar,
                type: bool,
                value: true,
            }
          # Show Tab bar in Finder
          - {
                domain: com.apple.finder,
                key: ShowTabView,
                type: bool,
                value: true,
            }
          # Show the hidden files
          - {
                domain: com.apple.finder,
                key: AppleShowAllFiles,
                type: string,
                value: "YES",
            }
          # change list view
          - {
                domain: com.apple.finder,
                key: FXPreferredViewStyle,
                type: string,
                value: "Nlsv",
            }
          # calculate all sizes
          - {
                domain: ExtendedListViewSettingsV2,
                key: calculateAllSizes,
                type: int,
                value: 1,
            }
          - {
                domain: ListViewSettings,
                key: calculateAllSizes,
                type: int,
                value: 1,
            }

          #################################
          # Dock
          #################################
          # Wipe all (default) app icons from the Dock
          #defaults write com.apple.dock persistent-apps -array
          - {
                domain: com.apple.dock,
                key: persistent-apps,
                type: array,
                value: [],
            }
          # auto hide dock (need "killall Dock")
          - { domain: com.apple.dock, key: autohide, type: bool, value: true }
          - {
                domain: com.apple.dock,
                key: autohide-time-modifier,
                type: int,
                value: 0,
            }
          # Move dock to left side
          - {
                domain: com.apple.dock,
                key: orientation,
                type: string,
                value: "left",
            }
          # Magnificate the dock
          - {
                domain: com.apple.dock,
                key: magnification,
                type: bool,
                value: true,
            }
          # Set the icon size
          # Magnificate the dock
          - { domain: com.apple.dock, key: tilesize, type: float, value: 25 }
          #################################
          # QuickLook
          #################################
          # Enable text selection in QuickLook
          - {
                domain: com.apple.finder,
                key: QLEnableTextSelection,
                type: bool,
                value: true,
            }
          #################################
          # Mission Control
          #################################
          # Enable App Expose Gesture
          - {
                domain: com.apple.dock,
                key: showAppExposeGestureEnabled,
                type: int,
                value: 1,
            }
          # Enable Mission Control Gesture
          - {
                domain: com.apple.dock,
                key: showMissionControlGestureEnabled,
                type: int,
                value: 1,
            }
          # Hot corners
          # Possible values:
          #  0: no-op
          #  2: Mission Control
          #  3: Show application windows
          #  4: Desktop
          #  5: Start screen saver
          #  6: Disable screen saver
          #  7: Dashboard
          # 10: Put display to sleep
          # 11: Launchpad
          # 12: Notification Center
          # 13: Lock Screen
          # Top left screen corner → Put display to sleep
          - {
                domain: com.apple.dock,
                key: wvous-tl-corner,
                type: int,
                value: 10,
            }
          - {
                domain: com.apple.dock,
                key: wvous-tl-modifier,
                type: int,
                value: 0,
            }
          # Top right screen corner → Desktop
          - {
                domain: com.apple.dock,
                key: wvous-tr-corner,
                type: int,
                value: 4,
            }
          - {
                domain: com.apple.dock,
                key: wvous-tr-modifier,
                type: int,
                value: 0,
            }
          # Bottom left screen corner → Mission Control
          - {
                domain: com.apple.dock,
                key: wvous-bl-corner,
                type: int,
                value: 2,
            }
          - {
                domain: com.apple.dock,
                key: wvous-bl-modifier,
                type: int,
                value: 0,
            }
          # Bottom right screen corner → Show application windows
          - {
                domain: com.apple.dock,
                key: wvous-br-corner,
                type: int,
                value: 3,
            }
          - {
                domain: com.apple.dock,
                key: wvous-br-modifier,
                type: int,
                value: 0,
            }
          #################################
          # Keyboard
          #################################
          # key repeat fast
          - {
                domain: "Apple Global Domain",
                key: KeyRepeat,
                type: float,
                value: 2,
            }
          # key delay
          - {
                domain: "Apple Global Domain",
                key: InitialKeyRepeat,
                type: float,
                value: 15,
            }
          #################################
          # Trackpad
          #################################
          # Enable 'Tap to click'
          - {
                domain: com.apple.AppleMultitouchTrackpad,
                key: Clicking,
                type: int,
                value: 1,
            }
          # trackpad first click threshold
          - {
                domain: com.apple.AppleMultitouchTrackpad,
                key: FirstClickThreshold,
                type: int,
                value: 0,
            }
          # trackpad second click threshold
          - {
                domain: com.apple.AppleMultitouchTrackpad,
                key: SecondClickThreshold,
                type: int,
                value: 0,
            }
          # swipe between apps with four fingers
          - {
                domain: com.apple.AppleMultitouchTrackpad,
                key: TrackpadFourFingerHorizSwipeGesture,
                type: int,
                value: 1,
            }
          # enable three finger drag
          - {
                domain: com.apple.AppleMultitouchTrackpad,
                key: TrackpadThreeFingerDrag,
                type: int,
                value: 1,
            }
          - {
                domain: com.apple.driver.AppleBluetoothMultitouch.trackpad,
                key: TrackpadThreeFingerDrag,
                type: int,
                value: 1,
            }
          # enable four finger vert swipe
          - {
                domain: com.apple.AppleMultitouchTrackpad,
                key: TrackpadFourFingerVertSwipeGesture,
                type: int,
                value: 1,
            }
          - {
                domain: com.apple.driver.AppleBluetoothMultitouch.trackpad,
                key: TrackpadFourFingerVertSwipeGesture,
                type: int,
                value: 1,
            }
          # tracking speed
          - {
                domain: "Apple Global Domain",
                key: com.apple.trackpad.scaling,
                type: float,
                value: 3,
            }
          #################################
          # Safari
          #################################
          # Enable the Develop menu in Safari
          - {
                domain: com.apple.Safari.SandboxBroker,
                key: ShowDevelopMenu,
                type: int,
                value: 1,
            }
          # Can not find full URL any more in 15.1
          # # Show the full URL in the address bar
          # - {
          #       domain: com.apple.Safari,
          #       key: ShowFullURLInSmartSearchField,
          #       type: bool,
          #       value: true,
          #   }
          # Add a context menu item for showing the `Web Inspector` in web views
          - {
                domain: NSGlobalDomain,
                key: WebKitDeveloperExtras,
                type: bool,
                value: true,
            }
          # Can not find Safari's status bar in 15.1
          # # Show Safari's Status Bar
          # - {
          #       domain: com.apple.Safari,
          #       key: ShowStatusBar,
          #       type: bool,
          #       value: true,
          #   }
          #################################
          # Other
          #################################
          # Show the battery percentage from the menu bar (need "killall SystemUIServer")
          - {
                domain: com.apple.menuextra.battery,
                key: ShowPercent,
                type: string,
                value: "YES",
            }
          # Avoid creating .DS_Store files on network or USB volumes
          - {
                domain: com.apple.desktopservices,
                key: DSDontWriteNetworkStores,
                type: bool,
                value: true,
            }
          - {
                domain: com.apple.desktopservices,
                key: DSDontWriteUSBStores,
                type: bool,
                value: true,
            }
          # Disable the "Are you sure you want to open this application?" dialog
          - {
                domain: com.apple.LaunchServices,
                key: LSQuarantine,
                type: bool,
                value: false,
            }
          # Disable disk image verification
          - {
                domain: com.apple.frameworks.diskimages,
                key: skip-verify,
                type: bool,
                value: true,
            }
          - {
                domain: com.apple.frameworks.diskimages,
                key: skip-verify-locked,
                type: bool,
                value: true,
            }
          - {
                domain: com.apple.frameworks.diskimages,
                key: skip-verify-remote,
                type: bool,
                value: true,
            }
          # Disable live conversion
          - {
                domain: com.apple.inputmethod.Kotoeri,
                key: JIMPrefLiveConversionKey,
                type: int,
                value: 0,
            }

  tasks:
      # brew update
      - name: update homebrew
        community.general.homebrew:
            update_homebrew: yes

      # brew
      - name: brew install
        ignore_errors: yes
        community.general.homebrew:
            name: "{{ item.name }}"
            state: present
        with_items: "{{ homebrew_packages }}"

      # cask
      - name: install homebrew cask packages
        ignore_errors: yes
        community.general.homebrew_cask:
            name: "{{ item.name }}"
            state: present
            install_options: "appdir=/Applications"
        with_items: "{{ homebrew_cask_packages }}"

      # mac app store
      - name: install mac app store apps
        ignore_errors: yes
        community.general.mas:
            id: "{{ item.id }}"
            state: present
        with_items: "{{ mac_app_store_apps }}"

      # mac settings
      - name: setup detault mac settings
        ignore_errors: yes
        osx_defaults: >
            domain={{ item.domain }}
            key={{ item.key }}
            type={{ item.type }}
            value={{ item.value }}
            state={{ item.state|default('present') }}
        with_items: "{{ osx_settings }}"

      # dotfiles
      # - name: Pull dotfiles
      #   git: repo=git@github.com:m2mt-l/dotfiles.git dest=~/dotfiles
      #   register: pull_dotfiles_result
      # - name: Copy dotfiles
      #   copy: src=~/dotfiles/{{ item }} dest=~/{{ item }} force=no
      #   with_items:
      #       - ".bashrc"
      #       - ".vimrc"
      #       - ".gitconfig"
      #   when: pull_dotfiles_result | changed

      # Show the ~/Library directory
      - name: show library directory
        command:
            cmd: chflags nohidden ~/Library
        check_mode: no
